name: Minecart_speedplus
main: fi.dy.esav.Minecart_speedplus.Minecart_speedplus
version: 2.0
commands:
   msp:
      description: Sets new minecart speed limit.
      usage: |
         /msp set <multiplier> | /msp verbose [true/false]
permissions:
    msp.*:
        description: Gives access to all msp features
        default: op
        children:
            msp.cmd: true
            msp.signs: true
    msp.cmd:
        description: Allows you to use speed cmd
        default: op
    msp.signs:
        description: Allows you to create both signs
        default: op
        children:
            msp.signs.speed: true
            msp.signs.fly: true
    msp.signs.speed:
        description: Allows you to create speed-sings
        default: op
    msp.signs.fly:
        description: Allows you to create fly-signs
        default: op
